// <auto-generated />
using System;
using System.Text.Json;
using Manito.Discord.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manito.Migrations
{
    [DbContext(typeof(DbContextImplementation))]
    [Migration("20221006184102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWall", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("WallName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MessageWalls");
                });

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWallLine", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("MessageWallID")
                        .HasColumnType("bigint");

                    b.Property<string>("WallLine")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MessageWallID");

                    b.ToTable("MessageWallLines");
                });

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWallTranslator", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CTranslation")
                        .HasColumnType("text");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long?>("MessageWallID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("MessageWallID");

                    b.ToTable("MessageWallTranslators");
                });

            modelBuilder.Entity("Manito.Discord.Shop.ShopItem", b =>
                {
                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("Manito.System.Economy.PlayerEconomyDeposit", b =>
                {
                    b.Property<decimal>("DiscordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("ChupatCurr")
                        .HasColumnType("bigint");

                    b.Property<long>("DonatCurr")
                        .HasColumnType("bigint");

                    b.Property<long>("ScalesCurr")
                        .HasColumnType("bigint");

                    b.HasKey("DiscordID");

                    b.ToTable("PlayerEconomyDeposits");
                });

            modelBuilder.Entity("Manito.System.Economy.PlayerEconomyWork", b =>
                {
                    b.Property<decimal>("DiscordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("LastWork")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimesWorked")
                        .HasColumnType("integer");

                    b.HasKey("DiscordID");

                    b.ToTable("PlayerWorks");
                });

            modelBuilder.Entity("Manito.System.Logging.LogLine", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LogLines");
                });

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWallLine", b =>
                {
                    b.HasOne("Manito.Discord.PermanentMessage.MessageWall", "MessageWall")
                        .WithMany("Msgs")
                        .HasForeignKey("MessageWallID");

                    b.Navigation("MessageWall");
                });

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWallTranslator", b =>
                {
                    b.HasOne("Manito.Discord.PermanentMessage.MessageWall", "MessageWall")
                        .WithMany()
                        .HasForeignKey("MessageWallID");

                    b.Navigation("MessageWall");
                });

            modelBuilder.Entity("Manito.Discord.PermanentMessage.MessageWall", b =>
                {
                    b.Navigation("Msgs");
                });
#pragma warning restore 612, 618
        }
    }
}
